#!/usr/bin/env python3
"""
add_coverage_picker - back-end support for the coverage checklist picker.

Refreshes coverage_loop.py (adds the 'only' filter) and patches loop.py so
--coverage accepts --only file::func. Run AFTER add_coverage_cmd.py, from the
folder with loop.py:

    python add_coverage_picker.py

Idempotent, with a backup. Pair it with the updated src/coverage.js (the
two-step file/function checklist).
"""

import base64
import os
import subprocess
import sys
import time

HERE = os.path.dirname(os.path.abspath(__file__))
_LOOP_B64 = """IyEvdXNyL2Jpbi9lbnYgcHl0aG9uMwoiIiIKY292ZXJhZ2VfbG9vcCAtIHRoZSBhZ2VudGljIGhh
bGYgb2YgdGhlIHVuaXQtdGVzdCBmZWF0dXJlLgoKICBzY2FuIC0+IGlkZW50aWZ5IGdhcHMgLT4g
dW5pdF90ZXN0ZXIgYWdlbnQgd3JpdGVzIGEgdGVzdCAtPiBSVU4gaXQgLT4KICBrZWVwIE9OTFkg
aWYgaXQgcGFzc2VzIC0+IHJlLXNjYW4gLT4gbXV0YXRpb24gLT4gcmVwb3J0IGJlZm9yZS9hZnRl
ci4KClRoZSBob3VzZSBydWxlLCBzYW1lIGFzIHRoZSByZXN0IG9mIERvY2tldDogdGhlIGFnZW50
IERFQ0lERVMsIGNvZGUgRU5GT1JDRVMuClRoZSB1bml0X3Rlc3RlciBhZ2VudCBwcm9wb3NlcyBh
IHRlc3Q7IHRoaXMgbG9vcCBwcm92ZXMgaXQgcnVucyBncmVlbiBiZWZvcmUKa2VlcGluZyBpdCwg
dGhlbiByZS1zY2FucyB0byBzaG93IGNvdmVyYWdlIGFjdHVhbGx5IG1vdmVkLCBhbmQgcnVucyBt
dXRhdGlvbiB0bwpwcm92ZSB0aGUga2VwdCB0ZXN0cyBhc3NlcnQgKG5vdCBqdXN0IGV4ZWN1dGUp
LiBBIHRlc3QgdGhhdCBlcnJvcnMgaXMgZGlzY2FyZGVkLgoKRGV0ZXJtaW5pc3RpYyBwYXJ0cyAo
c2NhbiwgcnVuLCByZS1zY2FuLCBtdXRhdGlvbiwgcmVwb3J0KSByZXVzZSBjb3ZlcmFnZV90b29s
CmFuZCBtdXRhdGlvbi4gVGhlIG9uZSBtb2RlbCBjYWxsIHBlciBmdW5jdGlvbiBnb2VzIHRocm91
Z2ggdHguY2hhdCwgZXhhY3RseSBsaWtlCmV2ZXJ5IG90aGVyIHN0YWdlIC0gc28gdGhpcyBydW5z
IHVuZGVyIGBsb29wLnB5IC0tY292ZXJhZ2VgIG9uIHRoZSBzYW1lIGdhdGV3YXkuCgpTZWxmLXRl
c3QgKG5vIG1vZGVsLCBubyBweXRlc3QsIG5vIGNvdmVyYWdlLnB5KTogIHB5dGhvbiBjb3ZlcmFn
ZV9sb29wLnB5IC0tc2VsZi10ZXN0CiIiIgoKZnJvbSBfX2Z1dHVyZV9fIGltcG9ydCBhbm5vdGF0
aW9ucwoKaW1wb3J0IGFyZ3BhcnNlCmltcG9ydCBqc29uCmltcG9ydCBzdWJwcm9jZXNzCmltcG9y
dCBzeXMKZnJvbSBwYXRobGliIGltcG9ydCBQYXRoCgpfaGVyZSA9IFBhdGgoX19maWxlX18pLnJl
c29sdmUoKS5wYXJlbnQKZm9yIF9wIGluIChfaGVyZSwgX2hlcmUucGFyZW50KToKICAgIGlmIHN0
cihfcCkgbm90IGluIHN5cy5wYXRoOgogICAgICAgIHN5cy5wYXRoLmluc2VydCgwLCBzdHIoX3Ap
KQoKdHJ5OgogICAgaW1wb3J0IHJvc3RlcgpleGNlcHQgRXhjZXB0aW9uOgogICAgcm9zdGVyID0g
Tm9uZQp0cnk6CiAgICBpbXBvcnQgYWdlbnRfbWVtb3J5CmV4Y2VwdCBFeGNlcHRpb246CiAgICBh
Z2VudF9tZW1vcnkgPSBOb25lCgpBR0VOVF9OQU1FID0gInVuaXRfdGVzdGVyIgoKCiMgLS0tLS0t
LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
LS0tIGhlbHBlcnMKCmRlZiBfcnVuKGNtZCwgY3dkKToKICAgIHJldHVybiBzdWJwcm9jZXNzLnJ1
bihjbWQsIGN3ZD1zdHIoY3dkKSwgc3Rkb3V0PXN1YnByb2Nlc3MuUElQRSwKICAgICAgICAgICAg
ICAgICAgICAgICAgICBzdGRlcnI9c3VicHJvY2Vzcy5TVERPVVQsIHRleHQ9VHJ1ZSkKCgpkZWYg
cGFyc2VfanNvbih0ZXh0KToKICAgICIiIlNhbWUgdG9sZXJhbnQgSlNPTiBleHRyYWN0aW9uIHRo
ZSBvdGhlciBhZ2VudHMgdXNlLiIiIgogICAgaWYgbm90IHRleHQ6CiAgICAgICAgcmFpc2UgVmFs
dWVFcnJvcigiZW1wdHkgbW9kZWwgcmVwbHkiKQogICAgcyA9IHRleHQuc3RyaXAoKQogICAgaWYg
cy5zdGFydHN3aXRoKCJgYGAiKToKICAgICAgICBzID0gcy5zcGxpdCgiYGBgIiwgMilbMV0gaWYg
cy5jb3VudCgiYGBgIikgPj0gMiBlbHNlIHMuc3RyaXAoImAiKQogICAgICAgIGlmIHMubHN0cmlw
KCkubG93ZXIoKS5zdGFydHN3aXRoKCJqc29uIik6CiAgICAgICAgICAgIHMgPSBzLmxzdHJpcCgp
WzQ6XQogICAgYSwgYiA9IHMuZmluZCgieyIpLCBzLnJmaW5kKCJ9IikKICAgIGlmIGEgPT0gLTEg
b3IgYiA9PSAtMSBvciBiIDwgYToKICAgICAgICByYWlzZSBWYWx1ZUVycm9yKCJubyBKU09OIG9i
amVjdCBpbiByZXBseSIpCiAgICByZXR1cm4ganNvbi5sb2FkcyhzW2E6YiArIDFdKQoKCmRlZiBy
ZWFkX3NvdXJjZShyZXBvLCBmdW5jKToKICAgICIiIlRoZSBmdW5jdGlvbidzIG93biBzb3VyY2Ug
cGx1cyB0aGUgZmlsZSdzIGltcG9ydCBsaW5lcywgc28gdGhlIGFnZW50IGhhcwogICAgd2hhdCBp
dCBuZWVkcyB0byB3cml0ZSBhbiBpbXBvcnRhYmxlIHRlc3Qgd2l0aG91dCBzZWVpbmcgdGhlIHdo
b2xlIHJlcG8uIiIiCiAgICB0cnk6CiAgICAgICAgbGluZXMgPSAoUGF0aChyZXBvKSAvIGZ1bmNb
ImZpbGUiXSkucmVhZF90ZXh0KGVuY29kaW5nPSJ1dGYtOCIpLnNwbGl0bGluZXMoKQogICAgZXhj
ZXB0IEV4Y2VwdGlvbjoKICAgICAgICByZXR1cm4gIiIKICAgIGltcG9ydHMgPSBbbG4gZm9yIGxu
IGluIGxpbmVzIGlmIGxuLnN0YXJ0c3dpdGgoKCJpbXBvcnQgIiwgImZyb20gIikpXVs6NDBdCiAg
ICBib2R5ID0gbGluZXNbZnVuY1sibGluZW5vIl0gLSAxOiBmdW5jWyJlbmRfbGluZW5vIl1dCiAg
ICByZXR1cm4gIiMgaW1wb3J0cyBpbiB7fTpcbnt9XG5cbiMgZnVuY3Rpb24gdW5kZXIgdGVzdDpc
bnt9Ii5mb3JtYXQoCiAgICAgICAgZnVuY1siZmlsZSJdLCAiXG4iLmpvaW4oaW1wb3J0cyksICJc
biIuam9pbihib2R5KSkKCgpkZWYgX3VzZXJfcHJvbXB0KGZ1bmMsIHNyYywgZGV0KToKICAgIHJl
dHVybiAoIkZJTEU6IHt9XG5GVU5DVElPTjoge30gIChsaW5lIHt9KVxuUFJJTUFSWSBMQU5HVUFH
RToge31cblxuIgogICAgICAgICAgICAiV3JpdGUgYSBmb2N1c2VkIHVuaXQgdGVzdCBmb3IgdGhp
cyBmdW5jdGlvbi5cblxue30iCiAgICAgICAgICAgICkuZm9ybWF0KGZ1bmNbImZpbGUiXSwgZnVu
Y1sibmFtZSJdLCBmdW5jWyJsaW5lbm8iXSwKICAgICAgICAgICAgICAgICAgICAgKGRldCBvciB7
fSkuZ2V0KCJwcmltYXJ5IiwgInB5dGhvbiIpLCBzcmMpCgoKZGVmIF9sb2FkX2FnZW50KHdvcmti
ZW5jaCwgY2ZnKToKICAgICIiIkxvYWQgdGhlIHVuaXRfdGVzdGVyIGFnZW50IHByb21wdC9tb2Rl
bCB0aGUgc2FtZSB3YXkgZXZlcnkgc3RhZ2UgZG9lcy4KICAgIEZhbGxzIGJhY2sgdG8gYSBidWls
dC1pbiBwcm9tcHQgaWYgdGhlIHJvc3RlciBpcyB1bmF2YWlsYWJsZSwgc28gdGhlIGxvb3AKICAg
IHN0aWxsIHJ1bnMgKHVzZWZ1bCBmb3IgLS1zZWxmLXRlc3QgYW5kIGJhcmUgY2hlY2tvdXRzKS4i
IiIKICAgIGlmIHJvc3RlciBpcyBub3QgTm9uZToKICAgICAgICB0cnk6CiAgICAgICAgICAgIEEg
PSByb3N0ZXIubG9hZChBR0VOVF9OQU1FLCB3b3JrYmVuY2gpCiAgICAgICAgICAgIGlmIGFnZW50
X21lbW9yeSBpcyBub3QgTm9uZToKICAgICAgICAgICAgICAgIEEgPSBhZ2VudF9tZW1vcnkuYXR0
YWNoKEEsIEFHRU5UX05BTUUsIGNmZy5nZXQoIl9wcm9qZWN0IiksIHdvcmtiZW5jaCkKICAgICAg
ICAgICAgcmV0dXJuIHsibW9kZWwiOiBBLmdldCgibW9kZWwiLCAid29ya2VyIiksICJwcm9tcHQi
OiBBLmdldCgicHJvbXB0IiwgX0ZBTExCQUNLKSwKICAgICAgICAgICAgICAgICAgICAic3RhbXAi
OiAocm9zdGVyLnN0YW1wKEEpIGlmIGhhc2F0dHIocm9zdGVyLCAic3RhbXAiKSBlbHNlICJ1bml0
X3Rlc3RlckAwIil9CiAgICAgICAgZXhjZXB0IEV4Y2VwdGlvbjoKICAgICAgICAgICAgcGFzcwog
ICAgcmV0dXJuIHsibW9kZWwiOiAid29ya2VyIiwgInByb21wdCI6IF9GQUxMQkFDSywgInN0YW1w
IjogInVuaXRfdGVzdGVyQDAifQoKCl9GQUxMQkFDSyA9ICgiWW91IHdyaXRlIG9uZSBmb2N1c2Vk
LCBwYXNzaW5nIHVuaXQgdGVzdCBmb3IgdGhlIGdpdmVuIGZ1bmN0aW9uLiAiCiAgICAgICAgICAg
ICAiUmV0dXJuIFNUUklDVCBKU09OOiB7XCJ0ZXN0X2ZpbGVcIjogXCJ0ZXN0L3VuaXQvdGVzdF88
eD4ucHlcIiwgIgogICAgICAgICAgICAgIlwidGVzdF9jb2RlXCI6IFwiPGNvbXBsZXRlIGltcG9y
dGFibGUgcHl0ZXN0IGZpbGU+XCIsIFwiY292ZXJzXCI6IFtcIjxmbj5cIl19IikKCgojIC0tLS0t
LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
LS0tLSBlbmZvcmNlCgpkZWYgX2FwcGx5X2FuZF92ZXJpZnkocmVwbywgZnVuYywgc3BlYywgY2Zn
LCBydW5fY21kLCBzYXkpOgogICAgIiIiV3JpdGUgdGhlIHByb3Bvc2VkIHRlc3QsIHJ1biBpdCwg
YW5kIEtFRVAgaXQgb25seSBpZiBpdCBwYXNzZXMuIEEgdGVzdAogICAgdGhhdCBlcnJvcnMgb3Ig
ZmFpbHMgaXMgcmVtb3ZlZCAtIHRoZSBhZ2VudCBkb2VzIG5vdCBnZXQgdG8gbGVhdmUgcmVkIHRl
c3RzCiAgICBiZWhpbmQuIFJldHVybnMgKGtlcHQ6IGJvb2wsIHJlYXNvbjogc3RyLCB0ZXN0X3Jl
bDogc3RyfE5vbmUpLiIiIgogICAgcmVsID0gc3BlYy5nZXQoInRlc3RfZmlsZSIpIG9yICgidGVz
dC91bml0L3Rlc3RfJXMucHkiICUgZnVuY1sibmFtZSJdKQogICAgcmVsID0gc3RyKHJlbCkucmVw
bGFjZSgiXFwiLCAiLyIpCiAgICBkZXN0ID0gUGF0aChyZXBvKSAvIHJlbAogICAgY29kZSA9IHNw
ZWMuZ2V0KCJ0ZXN0X2NvZGUiKSBvciAiIgogICAgaWYgbm90IGNvZGUuc3RyaXAoKToKICAgICAg
ICByZXR1cm4gRmFsc2UsICJubyB0ZXN0X2NvZGUiLCBOb25lCgogICAgcHJlX2V4aXN0aW5nID0g
ZGVzdC5leGlzdHMoKQogICAgYmFja3VwID0gTm9uZQogICAgdHJ5OgogICAgICAgIGlmIHByZV9l
eGlzdGluZzoKICAgICAgICAgICAgYmFja3VwID0gZGVzdC5yZWFkX3RleHQoZW5jb2Rpbmc9InV0
Zi04IikKICAgICAgICBkZXN0LnBhcmVudC5ta2RpcihwYXJlbnRzPVRydWUsIGV4aXN0X29rPVRy
dWUpCiAgICAgICAgZGVzdC53cml0ZV90ZXh0KGNvZGUsIGVuY29kaW5nPSJ1dGYtOCIpCiAgICBl
eGNlcHQgRXhjZXB0aW9uIGFzIGU6CiAgICAgICAgcmV0dXJuIEZhbHNlLCAiY291bGQgbm90IHdy
aXRlIHRlc3Q6ICVzIiAlIGUsIE5vbmUKCiAgICBjbWQgPSAoKGNmZyBvciB7fSkuZ2V0KCJjb3Zl
cmFnZSIpIG9yIHt9KS5nZXQoInRlc3RfY29tbWFuZF9zaW5nbGUiKSBvciBbCiAgICAgICAgc3lz
LmV4ZWN1dGFibGUsICItbSIsICJweXRlc3QiLCByZWwsICItcSJdCiAgICBwcm9jID0gcnVuX2Nt
ZChjbWQsIHJlcG8pCiAgICBvayA9IGdldGF0dHIocHJvYywgInJldHVybmNvZGUiLCAxKSA9PSAw
CgogICAgaWYgb2s6CiAgICAgICAgc2F5KCIgICsgJXMgLT4gJXMgKGdyZWVuLCBrZXB0KSIgJSAo
ZnVuY1sibmFtZSJdLCByZWwpKQogICAgICAgIHJldHVybiBUcnVlLCAicGFzc2VkIiwgcmVsCgog
ICAgIyByZXZlcnQ6IHJlc3RvcmUgYSBwcmUtZXhpc3RpbmcgZmlsZSwgb3IgcmVtb3ZlIHRoZSBv
bmUgd2UgYWRkZWQKICAgIHRyeToKICAgICAgICBpZiBwcmVfZXhpc3RpbmcgYW5kIGJhY2t1cCBp
cyBub3QgTm9uZToKICAgICAgICAgICAgZGVzdC53cml0ZV90ZXh0KGJhY2t1cCwgZW5jb2Rpbmc9
InV0Zi04IikKICAgICAgICBlbGlmIGRlc3QuZXhpc3RzKCk6CiAgICAgICAgICAgIGRlc3QudW5s
aW5rKCkKICAgIGV4Y2VwdCBFeGNlcHRpb246CiAgICAgICAgcGFzcwogICAgdGFpbCA9ICJcbiIu
am9pbigoZ2V0YXR0cihwcm9jLCAic3Rkb3V0IiwgIiIpIG9yICIiKS5zcGxpdGxpbmVzKClbLTQ6
XSkKICAgIHNheSgiICAtICVzIGRpc2NhcmRlZCAodGVzdCBub3QgZ3JlZW4pIiAlIGZ1bmNbIm5h
bWUiXSkKICAgIHJldHVybiBGYWxzZSwgInRlc3QgZGlkIG5vdCBwYXNzOiAlcyIgJSB0YWlsWzoy
MDBdLCBOb25lCgoKIyAtLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0gdGhlIGxvb3AKCmRlZiBydW4odHgsIGNmZywgcmVwbywg
d29ya2JlbmNoPU5vbmUsIGRiPU5vbmUsIHBhdGhzPU5vbmUsIG9ubHk9Tm9uZSwKICAgICAgICBt
YXhfZnVuY3Rpb25zPU5vbmUsIHNheT1Ob25lLCBydW5fY21kPU5vbmUsIHNjYW5fZm49Tm9uZSk6
CiAgICBzYXkgPSBzYXkgb3IgKGxhbWJkYSAqXzogTm9uZSkKICAgIHJ1bl9jbWQgPSBydW5fY21k
IG9yIF9ydW4KICAgIGlmIHNjYW5fZm4gaXMgTm9uZToKICAgICAgICBpbXBvcnQgY292ZXJhZ2Vf
dG9vbAogICAgICAgIHNjYW5fZm4gPSBjb3ZlcmFnZV90b29sLnNjYW4KICAgIGNmZyA9IGNmZyBv
ciB7fQoKICAgIGJlZm9yZSA9IHNjYW5fZm4ocmVwbywgY2ZnKQogICAgZGV0ID0gYmVmb3JlLmdl
dCgiZGV0ZWN0Iikgb3Ige30KICAgIGlmIG5vdCBiZWZvcmVbInJlcG9ydCJdLmdldCgic3VwcG9y
dGVkIiwgVHJ1ZSk6CiAgICAgICAgc2F5KCIgICIgKyAoYmVmb3JlWyJyZXBvcnQiXS5nZXQoInVu
c3VwcG9ydGVkX25vdGUiKSBvciAidW5zdXBwb3J0ZWQgcHJvamVjdCIpKQogICAgICAgIHJldHVy
biB7InN1cHBvcnRlZCI6IEZhbHNlLCAicmVwb3J0IjogYmVmb3JlWyJyZXBvcnQiXX0KCiAgICBw
ZW5kaW5nID0gbGlzdCgoYmVmb3JlLmdldCgiZ2FwcyIpIG9yIHt9KS5nZXQoInVudGVzdGVkIikg
b3IgW10pCiAgICBpZiBwYXRoczoKICAgICAgICB3YW50ID0ge3N0cihwKS5yZXBsYWNlKCJcXCIs
ICIvIikgZm9yIHAgaW4gcGF0aHN9CiAgICAgICAgcGVuZGluZyA9IFtmIGZvciBmIGluIHBlbmRp
bmcKICAgICAgICAgICAgICAgICAgIGlmIGZbImZpbGUiXSBpbiB3YW50IG9yIGFueShmWyJmaWxl
Il0uc3RhcnRzd2l0aCh3KSBmb3IgdyBpbiB3YW50KV0KICAgIGlmIG9ubHk6CiAgICAgICAgIyBl
eGFjdCBzZWxlY3Rpb24gZnJvbSB0aGUgcGlja2VyOiAiZmlsZTo6ZnVuYyIsIG9yIGEgYmFyZSBm
dW5jdGlvbiBuYW1lCiAgICAgICAga2V5cyA9IHNldChvbmx5KQogICAgICAgIHBlbmRpbmcgPSBb
ZiBmb3IgZiBpbiBwZW5kaW5nCiAgICAgICAgICAgICAgICAgICBpZiAoIiVzOjolcyIgJSAoZlsi
ZmlsZSJdLCBmWyJuYW1lIl0pKSBpbiBrZXlzIG9yIGZbIm5hbWUiXSBpbiBrZXlzXQogICAgaWYg
bWF4X2Z1bmN0aW9uczoKICAgICAgICBwZW5kaW5nID0gcGVuZGluZ1s6bWF4X2Z1bmN0aW9uc10K
CiAgICBiX2NvdiA9IGJlZm9yZVsicmVwb3J0Il0uZ2V0KCJjb3ZlcmFnZV9wZXJjZW50IikKICAg
IHNheSgiY292ZXJhZ2UgJXMlJSAtICVkIGZ1bmN0aW9uKHMpIHRvIHdyaXRlIHRlc3RzIGZvciIK
ICAgICAgICAlIChiX2NvdiwgbGVuKHBlbmRpbmcpKSkKCiAgICBBID0gX2xvYWRfYWdlbnQod29y
a2JlbmNoLCBjZmcpCiAgICBhZGRlZCwgc2tpcHBlZCA9IFtdLCBbXQogICAgZm9yIGZ1bmMgaW4g
cGVuZGluZzoKICAgICAgICBzcmMgPSByZWFkX3NvdXJjZShyZXBvLCBmdW5jKQogICAgICAgIGlm
IG5vdCBzcmM6CiAgICAgICAgICAgIHNraXBwZWQuYXBwZW5kKHsiZnVuYyI6IGZ1bmNbIm5hbWUi
XSwgIndoeSI6ICJjb3VsZCBub3QgcmVhZCBzb3VyY2UifSkKICAgICAgICAgICAgY29udGludWUK
ICAgICAgICB0cnk6CiAgICAgICAgICAgIHJlcGx5ID0gdHguY2hhdChBWyJtb2RlbCJdLCBBWyJw
cm9tcHQiXSwgX3VzZXJfcHJvbXB0KGZ1bmMsIHNyYywgZGV0KSkKICAgICAgICAgICAgc3BlYyA9
IHBhcnNlX2pzb24ocmVwbHkuZ2V0KCJ0ZXh0IiwgIiIpIGlmIGlzaW5zdGFuY2UocmVwbHksIGRp
Y3QpIGVsc2UgIiIpCiAgICAgICAgZXhjZXB0IEV4Y2VwdGlvbiBhcyBlOgogICAgICAgICAgICBz
a2lwcGVkLmFwcGVuZCh7ImZ1bmMiOiBmdW5jWyJuYW1lIl0sICJ3aHkiOiAiYWdlbnQvcGFyc2Ug
ZXJyb3I6ICVzIiAlIGV9KQogICAgICAgICAgICBjb250aW51ZQogICAgICAgIGtlcHQsIHdoeSwg
cmVsID0gX2FwcGx5X2FuZF92ZXJpZnkocmVwbywgZnVuYywgc3BlYywgY2ZnLCBydW5fY21kLCBz
YXkpCiAgICAgICAgaWYga2VwdDoKICAgICAgICAgICAgYWRkZWQuYXBwZW5kKHsiZnVuYyI6IGZ1
bmNbIm5hbWUiXSwgImZpbGUiOiBmdW5jWyJmaWxlIl0sICJ0ZXN0IjogcmVsfSkKICAgICAgICBl
bHNlOgogICAgICAgICAgICBza2lwcGVkLmFwcGVuZCh7ImZ1bmMiOiBmdW5jWyJuYW1lIl0sICJ3
aHkiOiB3aHl9KQoKICAgIGFmdGVyID0gc2Nhbl9mbihyZXBvLCBjZmcpCiAgICBhX2NvdiA9IGFm
dGVyWyJyZXBvcnQiXS5nZXQoImNvdmVyYWdlX3BlcmNlbnQiKQoKICAgIGNvdmVyZWRfZmlsZXMg
PSBzb3J0ZWQoe2ZbImZpbGUiXSBmb3IgZiBpbiAoYWZ0ZXIuZ2V0KCJnYXBzIikgb3Ige30pLmdl
dCgiY292ZXJlZCIsIFtdKX0pCiAgICBtdXQgPSB7ImtpbGxfcmF0ZSI6IE5vbmUsICJzdXJ2aXZl
ZCI6IDAsICJzdXJ2aXZvcnMiOiBbXSwgInNraXBwZWQiOiAibm8gY292ZXJlZCBjb2RlIn0KICAg
IGlmIGNvdmVyZWRfZmlsZXM6CiAgICAgICAgdHJ5OgogICAgICAgICAgICBpbXBvcnQgbXV0YXRp
b24KICAgICAgICAgICAgbWNmZyA9IGRpY3QoY2ZnKQogICAgICAgICAgICBtY2ZnWyJkZXZlbG9w
ZXIiXSA9IGRpY3QobWNmZy5nZXQoImRldmVsb3BlciIpIG9yIHt9KQogICAgICAgICAgICBtY2Zn
WyJkZXZlbG9wZXIiXVsidW5pdF9jb21tYW5kIl0gPSAoKGNmZy5nZXQoImNvdmVyYWdlIikgb3Ig
e30pLmdldCgKICAgICAgICAgICAgICAgICJ0ZXN0X2NvbW1hbmQiKSkgb3IgW3N5cy5leGVjdXRh
YmxlLCAiLW0iLCAicHl0ZXN0IiwgIi1xIl0KICAgICAgICAgICAgbXV0ID0gbXV0YXRpb24ucnVu
X211dGF0aW9uKHN0cihyZXBvKSwgY292ZXJlZF9maWxlcywgbWNmZykKICAgICAgICAgICAgbXV0
WyJza2lwcGVkIl0gPSBOb25lCiAgICAgICAgZXhjZXB0IEV4Y2VwdGlvbiBhcyBlOgogICAgICAg
ICAgICBtdXQgPSB7ImtpbGxfcmF0ZSI6IE5vbmUsICJzdXJ2aXZlZCI6IDAsICJzdXJ2aXZvcnMi
OiBbXSwKICAgICAgICAgICAgICAgICAgICJza2lwcGVkIjogIm11dGF0aW9uIGVycm9yOiAlcyIg
JSBlfQoKICAgIHNheSgiIikKICAgIHNheSgiY292ZXJhZ2UgJXMlJSAtPiAlcyUlICAgdGVzdHMg
YWRkZWQ6ICVkICAgc2tpcHBlZDogJWQiCiAgICAgICAgJSAoYl9jb3YsIGFfY292LCBsZW4oYWRk
ZWQpLCBsZW4oc2tpcHBlZCkpKQogICAgaWYgbXV0LmdldCgia2lsbF9yYXRlIikgaXMgbm90IE5v
bmU6CiAgICAgICAgc2F5KCJtdXRhdGlvbiBraWxsIHJhdGUgb24gbmV3IGNvdmVyYWdlOiAlLjBm
JSUgKCVkIHN1cnZpdm9yKHMpKSIKICAgICAgICAgICAgJSAoMTAwICogbXV0WyJraWxsX3JhdGUi
XSwgbXV0LmdldCgic3Vydml2ZWQiLCAwKSkpCgogICAgcmV0dXJuIHsKICAgICAgICAic3VwcG9y
dGVkIjogVHJ1ZSwKICAgICAgICAiYmVmb3JlX2NvdmVyYWdlIjogYl9jb3YsCiAgICAgICAgImFm
dGVyX2NvdmVyYWdlIjogYV9jb3YsCiAgICAgICAgInRlc3RzX2FkZGVkIjogYWRkZWQsCiAgICAg
ICAgInNraXBwZWQiOiBza2lwcGVkLAogICAgICAgICJtdXRhdGlvbl9raWxsX3JhdGUiOiBtdXQu
Z2V0KCJraWxsX3JhdGUiKSwKICAgICAgICAibXV0YXRpb25fc3Vydml2b3JzIjogKG11dC5nZXQo
InN1cnZpdm9ycyIpIG9yIFtdKVs6MjBdLAogICAgICAgICJzdGlsbF9wZW5kaW5nIjogW3siZmls
ZSI6IGZbImZpbGUiXSwgIm5hbWUiOiBmWyJuYW1lIl19CiAgICAgICAgICAgICAgICAgICAgICAg
ICAgZm9yIGYgaW4gKGFmdGVyLmdldCgiZ2FwcyIpIG9yIHt9KS5nZXQoInVudGVzdGVkIiwgW10p
XVs6MjAwXSwKICAgIH0KCgojID09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09IHNlbGYtdGVzdAoKY2xhc3MgX0Zha2VUeDoK
ICAgICIiIlJldHVybnMgYSBjYW5uZWQgdGVzdCB3aG9zZSBncmVlbm5lc3MgZGVwZW5kcyBvbiB0
aGUgZnVuY3Rpb24gbmFtZSwgc28gd2UKICAgIGNhbiBkcml2ZSBib3RoIHRoZSBrZXB0IGFuZCBk
aXNjYXJkZWQgcGF0aHMuIiIiCiAgICBkZWYgY2hhdChzZWxmLCBtb2RlbCwgc3lzdGVtLCB1c2Vy
KToKICAgICAgICBuYW1lID0gIiIKICAgICAgICBmb3IgbG4gaW4gdXNlci5zcGxpdGxpbmVzKCk6
CiAgICAgICAgICAgIGlmIGxuLnN0YXJ0c3dpdGgoIkZVTkNUSU9OOiIpOgogICAgICAgICAgICAg
ICAgbmFtZSA9IGxuLnNwbGl0KClbMV0KICAgICAgICBjb2RlID0gKCJkZWYgdGVzdF8lcygpOlxu
ICAgIGFzc2VydCBUcnVlXG4iICUgbmFtZSkKICAgICAgICByZXR1cm4geyJ0ZXh0IjoganNvbi5k
dW1wcyh7CiAgICAgICAgICAgICJ0ZXN0X2ZpbGUiOiAidGVzdC91bml0L3Rlc3RfJXMucHkiICUg
bmFtZSwKICAgICAgICAgICAgInRlc3RfY29kZSI6IGNvZGUsICJjb3ZlcnMiOiBbbmFtZV19KSwK
ICAgICAgICAgICAgIm1vZGVsIjogbW9kZWwsICJ0b2tlbnNfaW4iOiAzLCAidG9rZW5zX291dCI6
IDV9CgogICAgZGVmIHByb2dyZXNzKHNlbGYsIHQpOgogICAgICAgIHBhc3MKCgpkZWYgX3NlbGZf
dGVzdCgpOgogICAgaW1wb3J0IHRlbXBmaWxlCiAgICBjaGVja3MgPSBbXQoKICAgIGRlZiBvayhu
YW1lLCBjb25kKToKICAgICAgICBjaGVja3MuYXBwZW5kKChuYW1lLCBib29sKGNvbmQpKSkKCiAg
ICB3aXRoIHRlbXBmaWxlLlRlbXBvcmFyeURpcmVjdG9yeSgpIGFzIHRkOgogICAgICAgIHJlcG8g
PSBQYXRoKHRkKQogICAgICAgIChyZXBvIC8gInNyYyIpLm1rZGlyKCkKICAgICAgICAocmVwbyAv
ICJzcmMiIC8gIm0ucHkiKS53cml0ZV90ZXh0KAogICAgICAgICAgICAiZGVmIGtlZXAoYSk6XG4g
ICAgcmV0dXJuIGEgKyAxXG5cbmRlZiBkcm9wKGEpOlxuICAgIHJldHVybiBhIC0gMVxuIikKCiAg
ICAgICAgcGVuZGluZyA9IFsKICAgICAgICAgICAgeyJmaWxlIjogInNyYy9tLnB5IiwgIm5hbWUi
OiAia2VlcCIsICJsaW5lbm8iOiAxLCAiZW5kX2xpbmVubyI6IDJ9LAogICAgICAgICAgICB7ImZp
bGUiOiAic3JjL20ucHkiLCAibmFtZSI6ICJkcm9wIiwgImxpbmVubyI6IDQsICJlbmRfbGluZW5v
IjogNX0sCiAgICAgICAgXQoKICAgICAgICBkZWYgZmFrZV9zY2FuKHIsIGNmZyk6CiAgICAgICAg
ICAgICMgYmVmb3JlOiAwJSwgYm90aCBwZW5kaW5nOyBhZnRlcjogNTAlLCAna2VlcCcgbm93IGNv
dmVyZWQKICAgICAgICAgICAgZG9uZSA9IGdldGF0dHIoZmFrZV9zY2FuLCAiY2FsbGVkIiwgRmFs
c2UpCiAgICAgICAgICAgIGZha2Vfc2Nhbi5jYWxsZWQgPSBUcnVlCiAgICAgICAgICAgIGlmIG5v
dCBkb25lOgogICAgICAgICAgICAgICAgcmV0dXJuIHsiZGV0ZWN0IjogeyJwcmltYXJ5IjogInB5
dGhvbiJ9LAogICAgICAgICAgICAgICAgICAgICAgICAicmVwb3J0IjogeyJzdXBwb3J0ZWQiOiBU
cnVlLCAiY292ZXJhZ2VfcGVyY2VudCI6IDAuMH0sCiAgICAgICAgICAgICAgICAgICAgICAgICJn
YXBzIjogeyJ1bnRlc3RlZCI6IHBlbmRpbmcsICJwYXJ0aWFsIjogW10sICJjb3ZlcmVkIjogW119
fQogICAgICAgICAgICByZXR1cm4geyJkZXRlY3QiOiB7InByaW1hcnkiOiAicHl0aG9uIn0sCiAg
ICAgICAgICAgICAgICAgICAgInJlcG9ydCI6IHsic3VwcG9ydGVkIjogVHJ1ZSwgImNvdmVyYWdl
X3BlcmNlbnQiOiA1MC4wfSwKICAgICAgICAgICAgICAgICAgICAiZ2FwcyI6IHsidW50ZXN0ZWQi
OiBbcGVuZGluZ1sxXV0sICJwYXJ0aWFsIjogW10sCiAgICAgICAgICAgICAgICAgICAgICAgICAg
ICAgImNvdmVyZWQiOiBbcGVuZGluZ1swXV19fQoKICAgICAgICAjIHRlc3QgZm9yICdrZWVwJyBw
YXNzZXM7IHRlc3QgZm9yICdkcm9wJyBmYWlscwogICAgICAgIGRlZiBmYWtlX3J1bihjbWQsIGN3
ZCk6CiAgICAgICAgICAgIHJlbCA9IGNtZFstMl0gaWYgbGVuKGNtZCkgPj0gMiBlbHNlICIiCiAg
ICAgICAgICAgIHJjID0gMSBpZiAiZHJvcCIgaW4gcmVsIGVsc2UgMAogICAgICAgICAgICBvdXQg
PSAiMSBwYXNzZWQiIGlmIHJjID09IDAgZWxzZSAiMSBmYWlsZWQiCiAgICAgICAgICAgIHJldHVy
biB0eXBlKCJQIiwgKCksIHsic3Rkb3V0Ijogb3V0LCAicmV0dXJuY29kZSI6IHJjfSkoKQoKICAg
ICAgICByZXMgPSBydW4oX0Zha2VUeCgpLCB7fSwgc3RyKHJlcG8pLCB3b3JrYmVuY2g9c3RyKHJl
cG8pLAogICAgICAgICAgICAgICAgICBzYXk9bGFtYmRhICpfOiBOb25lLCBydW5fY21kPWZha2Vf
cnVuLCBzY2FuX2ZuPWZha2Vfc2NhbikKCiAgICAgICAgb2soImJlZm9yZS9hZnRlciBjb3ZlcmFn
ZSByZXBvcnRlZCIsIHJlc1siYmVmb3JlX2NvdmVyYWdlIl0gPT0gMC4wCiAgICAgICAgICAgYW5k
IHJlc1siYWZ0ZXJfY292ZXJhZ2UiXSA9PSA1MC4wKQogICAgICAgIG9rKCJncmVlbiB0ZXN0IGtl
cHQiLCBhbnkoYVsiZnVuYyJdID09ICJrZWVwIiBmb3IgYSBpbiByZXNbInRlc3RzX2FkZGVkIl0p
KQogICAgICAgIG9rKCJyZWQgdGVzdCBkaXNjYXJkZWQiLCBhbnkoc1siZnVuYyJdID09ICJkcm9w
IiBmb3IgcyBpbiByZXNbInNraXBwZWQiXSkpCiAgICAgICAgb2soImtlcHQgdGVzdCBmaWxlIHdy
aXR0ZW4iLCAocmVwbyAvICJ0ZXN0IiAvICJ1bml0IiAvICJ0ZXN0X2tlZXAucHkiKS5leGlzdHMo
KSkKICAgICAgICBvaygiZGlzY2FyZGVkIHRlc3QgZmlsZSByZW1vdmVkIiwgbm90IChyZXBvIC8g
InRlc3QiIC8gInVuaXQiIC8gInRlc3RfZHJvcC5weSIpLmV4aXN0cygpKQoKICAgICAgICAjIHVu
c3VwcG9ydGVkIHByb2plY3Qgc2hvcnQtY2lyY3VpdHMgY2xlYW5seQogICAgICAgIGRlZiB1bnN1
cF9zY2FuKHIsIGNmZyk6CiAgICAgICAgICAgIHJldHVybiB7InJlcG9ydCI6IHsic3VwcG9ydGVk
IjogRmFsc2UsICJ1bnN1cHBvcnRlZF9ub3RlIjogIm5vIHB5dGhvbiJ9fQogICAgICAgIHIyID0g
cnVuKF9GYWtlVHgoKSwge30sIHN0cihyZXBvKSwgc2Nhbl9mbj11bnN1cF9zY2FuLCBzYXk9bGFt
YmRhICpfOiBOb25lKQogICAgICAgIG9rKCJ1bnN1cHBvcnRlZCBwcm9qZWN0IGhhbmRsZWQiLCBy
Mlsic3VwcG9ydGVkIl0gaXMgRmFsc2UpCgogICAgICAgICMgYSBiYXRjaCBsaW1pdCBpcyBob25v
dXJlZAogICAgICAgIGZha2Vfc2Nhbi5jYWxsZWQgPSBGYWxzZQogICAgICAgIHIzID0gcnVuKF9G
YWtlVHgoKSwge30sIHN0cihyZXBvKSwgd29ya2JlbmNoPXN0cihyZXBvKSwgbWF4X2Z1bmN0aW9u
cz0xLAogICAgICAgICAgICAgICAgIHNheT1sYW1iZGEgKl86IE5vbmUsIHJ1bl9jbWQ9ZmFrZV9y
dW4sIHNjYW5fZm49ZmFrZV9zY2FuKQogICAgICAgIG9rKCJtYXhfZnVuY3Rpb25zIGxpbWl0cyB0
aGUgYmF0Y2giLAogICAgICAgICAgIGxlbihyM1sidGVzdHNfYWRkZWQiXSkgKyBsZW4ocjNbInNr
aXBwZWQiXSkgPT0gMSkKCiAgICAgICAgIyBvbmx5PSByZXN0cmljdHMgdG8gYW4gZXhhY3QgZmls
ZTo6ZnVuYyBzZWxlY3Rpb24gKHRoZSBwaWNrZXIncyBvdXRwdXQpCiAgICAgICAgZmFrZV9zY2Fu
LmNhbGxlZCA9IEZhbHNlCiAgICAgICAgcjQgPSBydW4oX0Zha2VUeCgpLCB7fSwgc3RyKHJlcG8p
LCB3b3JrYmVuY2g9c3RyKHJlcG8pLAogICAgICAgICAgICAgICAgIG9ubHk9WyJzcmMvbS5weTo6
ZHJvcCJdLCBzYXk9bGFtYmRhICpfOiBOb25lLAogICAgICAgICAgICAgICAgIHJ1bl9jbWQ9ZmFr
ZV9ydW4sIHNjYW5fZm49ZmFrZV9zY2FuKQogICAgICAgIHBpY2tlZCA9IFthWyJmdW5jIl0gZm9y
IGEgaW4gcjRbInRlc3RzX2FkZGVkIl1dICsgW3NbImZ1bmMiXSBmb3IgcyBpbiByNFsic2tpcHBl
ZCJdXQogICAgICAgIG9rKCJvbmx5PSByZXN0cmljdHMgdG8gdGhlIGNob3NlbiBmdW5jdGlvbiIs
IHBpY2tlZCA9PSBbImRyb3AiXSkKCiAgICAgICAgIyBwYXJzZV9qc29uIHRvbGVyYXRlcyBmZW5j
ZXMKICAgICAgICBvaygicGFyc2VfanNvbiByZWFkcyBmZW5jZWQganNvbiIsCiAgICAgICAgICAg
cGFyc2VfanNvbigiYGBganNvblxue1wiYVwiOjF9XG5gYGAiKVsiYSJdID09IDEpCgogICAgcGFz
c2VkID0gc3VtKDEgZm9yIF8sIGMgaW4gY2hlY2tzIGlmIGMpCiAgICBmb3IgbmFtZSwgYyBpbiBj
aGVja3M6CiAgICAgICAgcHJpbnQoIiAgW3t9XSB7fSIuZm9ybWF0KCJvayAiIGlmIGMgZWxzZSAi
WFgiLCBuYW1lKSkKICAgIHByaW50KCJcbnt9L3t9IGNoZWNrcyBwYXNzZWQiLmZvcm1hdChwYXNz
ZWQsIGxlbihjaGVja3MpKSkKICAgIHJldHVybiBwYXNzZWQgPT0gbGVuKGNoZWNrcykKCgpkZWYg
bWFpbihhcmd2PU5vbmUpOgogICAgYXAgPSBhcmdwYXJzZS5Bcmd1bWVudFBhcnNlcihkZXNjcmlw
dGlvbj0iRG9ja2V0IGNvdmVyYWdlIHdyaXRpbmcgbG9vcCIpCiAgICBhcC5hZGRfYXJndW1lbnQo
Ii0tc2VsZi10ZXN0IiwgYWN0aW9uPSJzdG9yZV90cnVlIikKICAgIGFyZ3MgPSBhcC5wYXJzZV9h
cmdzKGFyZ3YpCiAgICBpZiBhcmdzLnNlbGZfdGVzdDoKICAgICAgICBzeXMuZXhpdCgwIGlmIF9z
ZWxmX3Rlc3QoKSBlbHNlIDEpCiAgICBhcC5wcmludF9oZWxwKCkKCgppZiBfX25hbWVfXyA9PSAi
X19tYWluX18iOgogICAgbWFpbigpCg=="""

ARG_OLD = '''    ap.add_argument("--path", action="append", default=None,
                    help="limit --coverage to these files/dirs (repeatable)")'''
ARG_NEW = '''    ap.add_argument("--path", action="append", default=None,
                    help="limit --coverage to these files/dirs (repeatable)")
    ap.add_argument("--only", action="append", default=None,
                    help="limit --coverage to exact functions: file::func (repeatable)")'''

CALL_OLD = "                                   paths=a.path, max_functions=a.max_functions,"
CALL_NEW = "                                   paths=a.path, only=a.only, max_functions=a.max_functions,"


def main():
    loop = os.path.join(HERE, "loop.py")
    if not os.path.exists(loop):
        print("add_coverage_picker: no loop.py here (" + HERE + ").")
        return 2

    with open(os.path.join(HERE, "coverage_loop.py"), "wb") as f:
        f.write(base64.b64decode(_LOOP_B64.encode()))
    print("refreshed coverage_loop.py (only filter)")

    with open(loop, "r", encoding="utf-8") as f:
        src = f.read()

    if "if a.coverage:" not in src:
        print("loop.py has no --coverage entry yet - run add_coverage_cmd.py first.")
        return 3

    if "--only" in src and "only=a.only" in src:
        print("loop.py already accepts --only - nothing to do.")
    else:
        bak = loop + ".bak-" + time.strftime("%Y%m%d-%H%M%S")
        with open(bak, "w", encoding="utf-8") as f:
            f.write(src)
        changed = False
        if "--only" not in src:
            if src.count(ARG_OLD) == 1:
                src = src.replace(ARG_OLD, ARG_NEW); changed = True
                print("  + loop.py: --only argument")
            else:
                print("  ! could not find the --path argument to anchor --only")
                return 3
        if "only=a.only" not in src:
            if src.count(CALL_OLD) == 1:
                src = src.replace(CALL_OLD, CALL_NEW); changed = True
                print("  + loop.py: pass only=a.only into the loop")
            else:
                print("  ! could not find the coverage_loop.run call to pass --only")
                return 3
        if changed:
            with open(loop, "w", encoding="utf-8") as f:
                f.write(src)
            print("  (backed up -> " + os.path.basename(bak) + ")")

    pyc = os.path.join(HERE, "__pycache__")
    if os.path.isdir(pyc):
        for n in os.listdir(pyc):
            if n.startswith(("loop", "coverage_loop")):
                try:
                    os.remove(os.path.join(pyc, n))
                except OSError:
                    pass

    print("")
    print("=" * 60)
    ok = True
    for script in ("coverage_loop.py", "loop.py"):
        print("$ python " + script + " --self-test")
        r = subprocess.run([sys.executable, script, "--self-test"], cwd=HERE,
                           capture_output=True, text=True)
        out = (r.stdout or "") + (r.stderr or "")
        for ln in out.splitlines():
            if ("passed" in ln or "FAIL" in ln or "Error" in ln
                    or "Traceback" in ln or "XX" in ln):
                print("  " + ln)
        if r.returncode != 0:
            ok = False
    print("=" * 60)
    if ok:
        print("Done. Replace src/coverage.js with the updated version, reload the")
        print("VS Code window, and 'Docket: Scan Coverage' now opens the checklist.")
    else:
        print("A self-test flagged something above; .bak-* holds the original.")
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
