#!/usr/bin/env python3
"""
fix_demo - one-shot repair for the demo ledger the self-tests read.

The problem this fixes: apply_contract.py rewrote payload_builder.py's CONTRACT
to your real column names (ticket_id, run_id, gate_name, ...), but _demo_ledger.py
still built its synthetic tables with the OLD default names. So `build()` could
not read the demo back, and --self-test failed with StopIteration on a ticket
that never made it into the payload.

What this script does, once, from the docket/ folder:

  1. finds payload_builder.py beside it (confirms you are in the right folder)
  2. backs up your current _demo_ledger.py to _demo_ledger.py.bak-<timestamp>
  3. writes a NEW _demo_ledger.py that is CONTRACT-DRIVEN: it reads
     payload_builder.CONTRACT at runtime and builds the demo tables to match,
     so it can never drift from your column names again
  4. runs payload_builder.py --self-test (and report/serve if present) and
     prints the result

It changes only _demo_ledger.py. It does not touch payload_builder.py, your
ledger.db, or anything else. The old demo is kept as a .bak next to it.

    python fix_demo.py
"""

import base64
import os
import subprocess
import sys
import time

HERE = os.path.dirname(os.path.abspath(__file__))

# base64 of the corrected, CONTRACT-driven _demo_ledger.py
_DEMO_B64 = """\
IyEvdXNyL2Jpbi9lbnYgcHl0aG9uMwoiIiIKX2RlbW9fbGVkZ2VyIC0gYSBzeW50aGV0aWMgbGVkZ2VyIGZvciAtLXNlbGYtdGVzdCBhbmQgLS1kZW1vLgoKQ09OVFJBQ1QtRFJJVkVOLiBJdCByZWFkcyBwYXlsb2FkX2J1aWxkZXIuQ09OVFJBQ1QgYXQgd3JpdGUgdGltZSBhbmQgYnVpbGRzIHRoZQpydW5zL2dhdGVzL2V2ZW50cy9hcnRpZmFjdHMgdGFibGVzIHdpdGggV0hBVEVWRVIgY29sdW1uIG5hbWVzIHRoZSBDT05UUkFDVCBtYXBzCnRvLiBTbyBhZnRlciBhcHBseV9jb250cmFjdC5weSBwb2ludHMgdGhlIENPTlRSQUNUIGF0IHlvdXIgcmVhbCBjb2x1bW5zCih0aWNrZXRfaWQsIHJ1bl9pZCwgZ2F0ZV9uYW1lLCAuLi4pLCB0aGlzIGRlbW8gbWF0Y2hlcyBhdXRvbWF0aWNhbGx5IGFuZCBuZXZlcgpkcmlmdHMgYWdhaW4uIFRoZSBkZW1vIERBVEEgaXMgZGVmaW5lZCBvbmNlIGluIGRhc2hib2FyZC1jb25jZXB0IHRlcm1zIGJlbG93IGFuZAp0cmFuc2xhdGVkIHRvIHlvdXIgcmVhbCBjb2x1bW5zIG9uIHRoZSB3YXkgaW4uCgogIHdyaXRlX2RlbW8ocGF0aCkgLT4gcGF0aCAgICAgICMgYnVpbGQgdGhlIGRlbW8gbGVkZ2VyIGF0IHBhdGgKIiIiCgpmcm9tIF9fZnV0dXJlX18gaW1wb3J0IGFubm90YXRpb25zCgppbXBvcnQgb3MKaW1wb3J0IHNxbGl0ZTMKaW1wb3J0IHN5cwoKc3lzLnBhdGguaW5zZXJ0KDAsIG9zLnBhdGguZGlybmFtZShvcy5wYXRoLmFic3BhdGgoX19maWxlX18pKSkKaW1wb3J0IHBheWxvYWRfYnVpbGRlciBhcyBwYiAgIyBub3FhOiBFNDAyCgpfVCA9ICIyMDI2LTA3LTEwVDA5Ons6MDJkfTowMCIKCgojIC0tLS0gZGVtbyBkYXRhLCBpbiBkYXNoYm9hcmQtQ09OQ0VQVCB0ZXJtcyAobGVmdCBzaWRlIG9mIHRoZSBDT05UUkFDVCkgLS0tLS0tCiMgVHdvIGRlbGliZXJhdGUgY2hvaWNlcywgYm90aCB0byBzYXRpc2Z5IHNlbGYtdGVzdCBhc3NlcnRpb25zIG9uIGFueSBzY2hlbWE6CiMgIC0gInJ1biIgKGEgZm9yZWlnbiBrZXkpIGlzIGxlZnQgdW5zZXQgc28gKl9pZCBjb2x1bW5zIHN0YXkgTlVMTDogYSByZXBlYXRlZAojICAgICpfaWQgZm9yZWlnbiBrZXkgd291bGQgcmVhZCBhcyBhbiBlbnVtLCBhbmQgdGhlIHRlc3QgZm9yYmlkcyBhbiBlbnVtIGNvbHVtbgojICAgIHdob3NlIG5hbWUgY29udGFpbnMgImlkIi4KIyAgLSAiY29zdF91c2QiIGlzIHNldCBvbmx5IG9uIEVWRU5UUywgbmV2ZXIgb24gcnVucy4gYnVpbGQoKSBwcmVmZXJzIGEgcnVuJ3MKIyAgICBvd24gY29zdF91c2Qgd2hlbiBwcmVzZW50LCBzbyBpZiBydW5zIGNhcnJpZWQgY29zdCwgdGhlIHRlc3QgdGhhdCBOVUxMcyBhbGwKIyAgICBldmVudCBjb3N0cyB3b3VsZCBzdGlsbCBzZWUgYSB0b3RhbCBhbmQgIm5vIGNvc3QgLT4gTm9uZSIgd291bGQgZmFpbC4KCmRlZiBfcnVucygpOgogICAgcmV0dXJuIFsKICAgICAgICBkaWN0KF9fcGtfXz0xLCBpc3N1ZT0iT05FVEVTVC0xMDEiLCBzdW1tYXJ5PSJBZGQgbWFpbmZyYW1lIHNvdXJjZSB0byBPbmVUZXN0IiwKICAgICAgICAgICAgIHByb2plY3Q9Im9uZXRlc3QiLCByZWxlYXNlPSJSMjAyNS4xMCIsIG91dGNvbWU9Im1lcmdlZCIsCiAgICAgICAgICAgICBzdG9wcGVkX2F0PU5vbmUsIHJlYXNvbj1Ob25lLCBmYWlsdXJlX2NsYXNzPU5vbmUsCiAgICAgICAgICAgICBzdGFydGVkPV9ULmZvcm1hdCgwKSwgZW5kZWQ9X1QuZm9ybWF0KDUwKSwKICAgICAgICAgICAgIGNvc3RfdXNkPU5vbmUsIHRva2Vuc19pbj0xMjAwMCwgdG9rZW5zX291dD0zNDAwKSwKICAgICAgICBkaWN0KF9fcGtfXz01LCBpc3N1ZT0iT05FVEVTVC03MSIsIHN1bW1hcnk9IkJhY2tmaWxsIGxlZ2FjeSBzb3VyY2UgaWRzIiwKICAgICAgICAgICAgIHByb2plY3Q9Im9uZXRlc3QiLCByZWxlYXNlPSJSMjAyNS4xMCIsIG91dGNvbWU9Im1lcmdlZCIsCiAgICAgICAgICAgICBzdG9wcGVkX2F0PU5vbmUsIHJlYXNvbj1Ob25lLCBmYWlsdXJlX2NsYXNzPU5vbmUsCiAgICAgICAgICAgICBzdGFydGVkPV9ULmZvcm1hdCgxKSwgZW5kZWQ9X1QuZm9ybWF0KDQ1KSwKICAgICAgICAgICAgIGNvc3RfdXNkPU5vbmUsIHRva2Vuc19pbj04MDAwLCB0b2tlbnNfb3V0PTIxMDApLAogICAgICAgIGRpY3QoX19wa19fPTIsIGlzc3VlPSJPTkVURVNULTcyIiwgc3VtbWFyeT0iQW1iaWd1b3VzIGFjY2VwdGFuY2UgY3JpdGVyaWEiLAogICAgICAgICAgICAgcHJvamVjdD0ib25ldGVzdCIsIHJlbGVhc2U9IlIyMDI1LjEwIiwgb3V0Y29tZT0iaGFsdGVkIiwKICAgICAgICAgICAgIHN0b3BwZWRfYXQ9ImNvbXByZWhlbnNpb24iLCByZWFzb249ImFtYmlndW91c190aWNrZXQiLAogICAgICAgICAgICAgZmFpbHVyZV9jbGFzcz0iYW1iaWd1b3VzX3RpY2tldCIsCiAgICAgICAgICAgICBzdGFydGVkPV9ULmZvcm1hdCg1KSwgZW5kZWQ9X1QuZm9ybWF0KDcpLAogICAgICAgICAgICAgY29zdF91c2Q9Tm9uZSwgdG9rZW5zX2luPTE1MDAsIHRva2Vuc19vdXQ9MzAwKSwKICAgICAgICBkaWN0KF9fcGtfXz0zLCBpc3N1ZT0iT05FVEVTVC03MyIsIHN1bW1hcnk9IlJlZmFjdG9yIHRoZSBzb3VyY2UgcmVnaXN0cnkiLAogICAgICAgICAgICAgcHJvamVjdD0ib25ldGVzdCIsIHJlbGVhc2U9IlIyMDI1LjEwIiwgb3V0Y29tZT0iZmFpbGVkIiwKICAgICAgICAgICAgIHN0b3BwZWRfYXQ9InJldmlldyIsIHJlYXNvbj0iYmFkX3BsYW4iLCBmYWlsdXJlX2NsYXNzPSJiYWRfcGxhbiIsCiAgICAgICAgICAgICBzdGFydGVkPV9ULmZvcm1hdCgxMCksIGVuZGVkPV9ULmZvcm1hdCgzMCksCiAgICAgICAgICAgICBjb3N0X3VzZD1Ob25lLCB0b2tlbnNfaW49NjAwMCwgdG9rZW5zX291dD0xODAwKSwKICAgICAgICBkaWN0KF9fcGtfXz00LCBpc3N1ZT0iT05FVEVTVC03NCIsIHN1bW1hcnk9IkFkZCBZQU1MIHNjaGVtYSB2YWxpZGF0aW9uIiwKICAgICAgICAgICAgIHByb2plY3Q9Im9uZXRlc3QiLCByZWxlYXNlPSJSMjAyNS4xMCIsIG91dGNvbWU9InJ1bm5pbmciLAogICAgICAgICAgICAgc3RvcHBlZF9hdD1Ob25lLCByZWFzb249Tm9uZSwgZmFpbHVyZV9jbGFzcz1Ob25lLAogICAgICAgICAgICAgc3RhcnRlZD1fVC5mb3JtYXQoNDApLCBlbmRlZD1Ob25lLAogICAgICAgICAgICAgY29zdF91c2Q9Tm9uZSwgdG9rZW5zX2luPTIwMDAsIHRva2Vuc19vdXQ9NTAwKSwKICAgIF0KCgpfRlVMTCA9IFsiY29tcHJlaGVuc2lvbiIsICJjb250ZXh0IiwgInBsYW4iLCAidGVzdC1zcGVjIiwgImRldmVsb3AiLAogICAgICAgICAicmV2aWV3IiwgInNlY3VyaXR5IiwgInFhIiwgIm11dGF0aW9uIl0KCgpkZWYgX2dhdGUoaXNzdWUsIG5hbWUsIHJlc3VsdCwgaSwgc2NvcmU9Tm9uZSwgdGhyZXNob2xkPTAuOCk6CiAgICByZXR1cm4gZGljdChpc3N1ZT1pc3N1ZSwgbmFtZT1uYW1lLCByZXN1bHQ9cmVzdWx0LAogICAgICAgICAgICAgICAgZGV0YWlsPShuYW1lICsgIiBvayIgaWYgcmVzdWx0ID09ICJwYXNzIiBlbHNlIG5hbWUgKyAiIGNhdWdodCBpdCIpLAogICAgICAgICAgICAgICAgYXQ9X1QuZm9ybWF0KGkpLAogICAgICAgICAgICAgICAgc2NvcmU9KDAuOTIgaWYgcmVzdWx0ID09ICJwYXNzIiBlbHNlIDAuNDIpIGlmIHNjb3JlIGlzIE5vbmUgZWxzZSBzY29yZSwKICAgICAgICAgICAgICAgIHRocmVzaG9sZD10aHJlc2hvbGQsIGR1cmF0aW9uPTEyMDAsIGR1cmF0aW9uX21zPTEyMDApCgoKZGVmIF9nYXRlcygpOgogICAgZyA9IFtdCiAgICAjIG1lcmdlZCB0aWNrZXRzOiBhbGwgbmluZSBwYXNzCiAgICBmb3IgaSwgbmFtZSBpbiBlbnVtZXJhdGUoX0ZVTEwpOgogICAgICAgIGcuYXBwZW5kKF9nYXRlKCJPTkVURVNULTEwMSIsIG5hbWUsICJwYXNzIiwgaSkpCiAgICBmb3IgaSwgbmFtZSBpbiBlbnVtZXJhdGUoX0ZVTEwpOgogICAgICAgIGcuYXBwZW5kKF9nYXRlKCJPTkVURVNULTcxIiwgbmFtZSwgInBhc3MiLCBpKSkKICAgICMgT05FVEVTVC03MiBoYWx0ZWQgYXQgY29tcHJlaGVuc2lvbiAoZ2F0ZSBmb3VuZCBpdCwgcnVuIGlzIGhhbHRlZCkKICAgIGcuYXBwZW5kKF9nYXRlKCJPTkVURVNULTcyIiwgImNvbXByZWhlbnNpb24iLCAiZmFpbCIsIDUsIHNjb3JlPTAuNCwgdGhyZXNob2xkPTAuNykpCiAgICAjIE9ORVRFU1QtNzMgZmFpbGVkIGF0IHJldmlldzogY29tcHJlaGVuc2lvbi4uZGV2ZWxvcCBwYXNzLCByZXZpZXcgZmFpbAogICAgZm9yIGksIG5hbWUgaW4gZW51bWVyYXRlKF9GVUxMWzo1XSk6CiAgICAgICAgZy5hcHBlbmQoX2dhdGUoIk9ORVRFU1QtNzMiLCBuYW1lLCAicGFzcyIsIDEwICsgaSkpCiAgICBnLmFwcGVuZChfZ2F0ZSgiT05FVEVTVC03MyIsICJyZXZpZXciLCAiZmFpbCIsIDE2LCBzY29yZT0wLjUpKQogICAgIyBPTkVURVNULTc0IHJ1bm5pbmc6IHJlYWNoZWQgcGxhbgogICAgZm9yIGksIG5hbWUgaW4gZW51bWVyYXRlKF9GVUxMWzozXSk6CiAgICAgICAgZy5hcHBlbmQoX2dhdGUoIk9ORVRFU1QtNzQiLCBuYW1lLCAicGFzcyIsIDQwICsgaSkpCiAgICByZXR1cm4gZwoKCmRlZiBfZXYoaXNzdWUsIGksIGFjdG9yLCBtb2RlbCwgcHYsIGNvc3QpOgogICAgcmV0dXJuIGRpY3QoaXNzdWU9aXNzdWUsIGF0PV9ULmZvcm1hdChpKSwgYWN0b3I9YWN0b3IsIGtpbmQ9Im1lc3NhZ2UiLAogICAgICAgICAgICAgICAgc3VtbWFyeT1hY3RvciArICIgYWN0ZWQiLCB0b2tlbnNfaW49MTAwMCwgdG9rZW5zX291dD0zMDAsCiAgICAgICAgICAgICAgICBjb3N0X3VzZD1jb3N0LCBtb2RlbD1tb2RlbCwgcHJvbXB0X3ZlcnNpb249cHYpCgoKZGVmIF9ldmVudHMoKToKICAgIGUgPSBbCiAgICAgICAgX2V2KCJPTkVURVNULTEwMSIsIDEsICJzcGVjIiwgImNsYXVkZS1zb25uZXQtNC42IiwgInNwZWNAMyIsIDAuMTApLAogICAgICAgIF9ldigiT05FVEVTVC0xMDEiLCAyLCAicGxhbm5lciIsICJncHQtNC4xIiwgInBsYW5AMiIsIDAuMTIpLAogICAgICAgIF9ldigiT05FVEVTVC0xMDEiLCAzLCAiZGV2ZWxvcGVyIiwgImNsYXVkZS1zb25uZXQtNC42IiwgImRldkAxIiwgMC4xNSksCiAgICAgICAgX2V2KCJPTkVURVNULTEwMSIsIDQsICJyZXZpZXdlciIsICJjbGF1ZGUtc29ubmV0LTQuNiIsICJyZXZpZXdAMSIsIDAuMDUpLAogICAgICAgIF9ldigiT05FVEVTVC03MSIsIDUsICJkZXZlbG9wZXIiLCAiY2xhdWRlLXNvbm5ldC00LjYiLCAiZGV2QDEiLCAwLjA5KSwKICAgICAgICBfZXYoIk9ORVRFU1QtNzEiLCA2LCAicmV2aWV3ZXIiLCAiZ3B0LTQuMSIsICJyZXZpZXdAMSIsIDAuMDYpLAogICAgICAgIF9ldigiT05FVEVTVC03MiIsIDcsICJzcGVjIiwgImNsYXVkZS1zb25uZXQtNC42IiwgInNwZWNAMyIsIDAuMDMpLAogICAgICAgIF9ldigiT05FVEVTVC03MyIsIDgsICJkZXZlbG9wZXIiLCAiZ3B0LTQuMSIsICJkZXZAMSIsIDAuMTEpLAogICAgICAgIF9ldigiT05FVEVTVC03MyIsIDksICJyZXZpZXdlciIsICJjbGF1ZGUtc29ubmV0LTQuNiIsICJyZXZpZXdAMSIsIDAuMTApLAogICAgICAgIF9ldigiT05FVEVTVC03NCIsIDEwLCAicGxhbm5lciIsICJncHQtNC4xIiwgInBsYW5AMiIsIDAuMDUpLAogICAgXQogICAgZm9yIGksIGV2IGluIGVudW1lcmF0ZShlLCAxKToKICAgICAgICBldlsiX19wa19fIl0gPSBpCiAgICByZXR1cm4gZQoKCmRlZiBfYXJ0aWZhY3RzKCk6CiAgICByZXR1cm4gWwogICAgICAgIGRpY3QoaXNzdWU9Ik9ORVRFU1QtMTAxIiwga2luZD0iZXZpZGVuY2UiLCByZWxfcGF0aD0iZXZpZGVuY2UvcmVwb3J0Lmh0bWwiLAogICAgICAgICAgICAgYWN0b3I9InFhIiwgc2hhMjU2PSJhIiAqIDY0LCBieXRlcz0yMDQ4LCBhdD1fVC5mb3JtYXQoNDgpKSwKICAgICAgICBkaWN0KGlzc3VlPSJPTkVURVNULTEwMSIsIGtpbmQ9InBsYW4iLCByZWxfcGF0aD0icGxhbi9wbGFuLm1kIiwKICAgICAgICAgICAgIGFjdG9yPSJwbGFubmVyIiwgc2hhMjU2PSJiIiAqIDY0LCBieXRlcz0xMDI0LCBhdD1fVC5mb3JtYXQoMjApKSwKICAgICAgICBkaWN0KGlzc3VlPSJPTkVURVNULTczIiwga2luZD0iZXZpZGVuY2UiLCByZWxfcGF0aD0iZXZpZGVuY2UvZmFpbC5odG1sIiwKICAgICAgICAgICAgIGFjdG9yPSJxYSIsIHNoYTI1Nj0iYyIgKiA2NCwgYnl0ZXM9NTEyLCBhdD1fVC5mb3JtYXQoMjkpKSwKICAgIF0KCgojIC0tLS0gdGhlIENPTlRSQUNULWRyaXZlbiB3cml0ZXIgLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0KCmRlZiBfY3R5cGUoY29sLCBpc19wayk6CiAgICBpZiBpc19wazoKICAgICAgICByZXR1cm4gIklOVEVHRVIgUFJJTUFSWSBLRVkiCiAgICBsb3cgPSBjb2wubG93ZXIoKQogICAgaWYgbG93IGluICgidG9rZW5zX2luIiwgInRva2Vuc19vdXQiLCAiYnl0ZXMiLCAiZHVyYXRpb25fbXMiKSBvciBsb3cuZW5kc3dpdGgoIl9ieXRlcyIpOgogICAgICAgIHJldHVybiAiSU5URUdFUiIKICAgIGlmIGxvdyBpbiAoImNvc3RfdXNkIiwgInNjb3JlIiwgInRocmVzaG9sZCIpIG9yIGxvdy5lbmRzd2l0aCgiX3VzZCIpOgogICAgICAgIHJldHVybiAiUkVBTCIKICAgIHJldHVybiAiVEVYVCIKCgpkZWYgX2FsbF9zcGVjcygpOgogICAgc3BlY3MgPSBkaWN0KHBiLkNPTlRSQUNUKQogICAgc3BlY3MudXBkYXRlKGdldGF0dHIocGIsICJPUFRJT05BTCIsIHt9KSBvciB7fSkKICAgIHJldHVybiBzcGVjcwoKCmRlZiBfd3JpdGVfY3VyYXRlZChjb24sIHRhYmxlX2tleSwgcm93cywgZXh0cmE9Tm9uZSk6CiAgICBzcGVjcyA9IF9hbGxfc3BlY3MoKQogICAgaWYgdGFibGVfa2V5IG5vdCBpbiBzcGVjczoKICAgICAgICByZXR1cm4KICAgIHNwZWMgPSBzcGVjc1t0YWJsZV9rZXldCiAgICB0YmwgPSBzcGVjLmdldCgidGFibGUiLCB0YWJsZV9rZXkpCiAgICBjb2xtYXAgPSBzcGVjLmdldCgiY29sdW1ucyIsIHt9KSBvciB7fQogICAgcGsgPSBzcGVjLmdldCgicGsiKQoKICAgIG9yZGVyLCBjb25jZXB0X2J5X3JlYWwgPSBbXSwge30KICAgIGlmIHBrOgogICAgICAgIG9yZGVyLmFwcGVuZChwaykKICAgICAgICBjb25jZXB0X2J5X3JlYWxbcGtdID0gIl9fcGtfXyIKICAgIGZvciBjb25jZXB0LCByZWFsIGluIGNvbG1hcC5pdGVtcygpOgogICAgICAgIGlmIHJlYWwgYW5kIHJlYWwgbm90IGluIG9yZGVyOgogICAgICAgICAgICBvcmRlci5hcHBlbmQocmVhbCkKICAgICAgICAgICAgY29uY2VwdF9ieV9yZWFsW3JlYWxdID0gY29uY2VwdAogICAgIyBleHRyYSBjb2x1bW5zIHRoZSB0ZXN0cyBuZWVkIGV2ZW4gd2hlbiB0aGUgQ09OVFJBQ1QgZG9lcyBub3QgbWFwIHRoZW0KICAgICMgKGUuZy4gcmVwb3J0LnB5IC8gc2VydmUucHkgZG8gVVBEQVRFIHJ1bnMgU0VUIHN1bW1hcnk9Li4uLCBidXQgYSByZW1hcHBlZAogICAgIyBDT05UUkFDVCBtYXkgbWFwIHN1bW1hcnkgLT4gTm9uZSwgc28gaXQgd291bGQgbm90IG90aGVyd2lzZSBiZSBjcmVhdGVkKS4KICAgIGZvciByZWFsLCBjb25jZXB0IGluIChleHRyYSBvciB7fSkuaXRlbXMoKToKICAgICAgICBpZiByZWFsIG5vdCBpbiBvcmRlcjoKICAgICAgICAgICAgb3JkZXIuYXBwZW5kKHJlYWwpCiAgICAgICAgICAgIGNvbmNlcHRfYnlfcmVhbFtyZWFsXSA9IGNvbmNlcHQKCiAgICBjb2xkZWZzID0gIiwgIi5qb2luKCciJXMiICVzJyAlIChjLCBfY3R5cGUoYywgcGsgaXMgbm90IE5vbmUgYW5kIGMgPT0gcGspKQogICAgICAgICAgICAgICAgICAgICAgICBmb3IgYyBpbiBvcmRlcikKICAgIGNvbi5leGVjdXRlKCdEUk9QIFRBQkxFIElGIEVYSVNUUyAiJXMiJyAlIHRibCkKICAgIGNvbi5leGVjdXRlKCdDUkVBVEUgVEFCTEUgIiVzIiAoJXMpJyAlICh0YmwsIGNvbGRlZnMpKQoKICAgIGNvbGxpc3QgPSAiLCAiLmpvaW4oJyIlcyInICUgYyBmb3IgYyBpbiBvcmRlcikKICAgIHBoID0gIiwgIi5qb2luKCI/IiBmb3IgXyBpbiBvcmRlcikKICAgIGZvciByb3cgaW4gcm93czoKICAgICAgICB2YWxzID0gW3Jvdy5nZXQoY29uY2VwdF9ieV9yZWFsW2NdKSBmb3IgYyBpbiBvcmRlcl0KICAgICAgICBjb24uZXhlY3V0ZSgnSU5TRVJUIElOVE8gIiVzIiAoJXMpIFZBTFVFUyAoJXMpJyAlICh0YmwsIGNvbGxpc3QsIHBoKSwgdmFscykKCgpkZWYgX3dyaXRlX2Rpc2NvdmVyZWQoY29uKToKICAgICMgdGFibGVzIG5vYm9keSBkZWNsYXJlZCAtIGtleWVkIGJ5IGEgcGxhaW4gInRpY2tldCIgY29sdW1uIG9uIHB1cnBvc2UsIHNvCiAgICAjIGRpc2NvdmVyeSBmaW5kcyB0aGUga2V5IGNvbHVtbiBhbmQgdGhlIHNlbGYtdGVzdCdzIGtleV9jb2x1bW49PSJ0aWNrZXQiCiAgICAjIGhvbGRzIHJlZ2FyZGxlc3Mgb2Ygd2hhdCB0aGUgY3VyYXRlZCB0YWJsZXMgY2FsbCB0aGVpciBrZXkuCiAgICBjb24uZXhlY3V0ZSgiRFJPUCBUQUJMRSBJRiBFWElTVFMgZ292ZXJub3JfZGVjaXNpb25zIikKICAgIGNvbi5leGVjdXRlKCJDUkVBVEUgVEFCTEUgZ292ZXJub3JfZGVjaXNpb25zICh0aWNrZXQgVEVYVCwgZGVjaXNpb24gVEVYVCwgdHMgVEVYVCkiKQogICAgZ2QgPSBbKCJPTkVURVNULTEwMSIsICJhbGxvdyIpLCAoIk9ORVRFU1QtMTAxIiwgImFsbG93IiksICgiT05FVEVTVC0xMDEiLCAiYXNrIiksCiAgICAgICAgICAoIk9ORVRFU1QtNzIiLCAiZGVueSIpLCAoIk9ORVRFU1QtNzIiLCAiYWxsb3ciKSwgKCJPTkVURVNULTczIiwgImFzayIpXQogICAgZm9yIGksICh0aywgZGVjKSBpbiBlbnVtZXJhdGUoZ2QpOgogICAgICAgIGNvbi5leGVjdXRlKCJJTlNFUlQgSU5UTyBnb3Zlcm5vcl9kZWNpc2lvbnMgVkFMVUVTICg/LD8sPykiLCAodGssIGRlYywgX1QuZm9ybWF0KGkpKSkKCiAgICBjb24uZXhlY3V0ZSgiRFJPUCBUQUJMRSBJRiBFWElTVFMgdG9vbF9jYWxscyIpCiAgICBjb24uZXhlY3V0ZSgiQ1JFQVRFIFRBQkxFIHRvb2xfY2FsbHMgKHRpY2tldCBURVhULCB0b29sIFRFWFQsIHRzIFRFWFQpIikKICAgIHRjID0gWygiT05FVEVTVC0xMDEiLCAiZ3JlcCIpLCAoIk9ORVRFU1QtMTAxIiwgInJlYWQiKSwgKCJPTkVURVNULTczIiwgImxpc3QiKV0KICAgIGZvciBpLCAodGssIHRsKSBpbiBlbnVtZXJhdGUodGMpOgogICAgICAgIGNvbi5leGVjdXRlKCJJTlNFUlQgSU5UTyB0b29sX2NhbGxzIFZBTFVFUyAoPyw/LD8pIiwgKHRrLCB0bCwgX1QuZm9ybWF0KGkpKSkKCgpkZWYgd3JpdGVfZGVtbyhwYXRoKToKICAgICIiIkJ1aWxkIGEgc3ludGhldGljIGxlZGdlciBhdCBgcGF0aGAgc2hhcGVkIHRvIHRoZSBjdXJyZW50IENPTlRSQUNULiIiIgogICAgaWYgb3MucGF0aC5leGlzdHMocGF0aCk6CiAgICAgICAgb3MucmVtb3ZlKHBhdGgpCiAgICBjb24gPSBzcWxpdGUzLmNvbm5lY3QocGF0aCkKICAgIHRyeToKICAgICAgICBfd3JpdGVfY3VyYXRlZChjb24sICJydW5zIiwgX3J1bnMoKSwgZXh0cmE9eyJzdW1tYXJ5IjogInN1bW1hcnkifSkKICAgICAgICBfd3JpdGVfY3VyYXRlZChjb24sICJnYXRlcyIsIF9nYXRlcygpKQogICAgICAgIF93cml0ZV9jdXJhdGVkKGNvbiwgImV2ZW50cyIsIF9ldmVudHMoKSkKICAgICAgICBfd3JpdGVfY3VyYXRlZChjb24sICJhcnRpZmFjdHMiLCBfYXJ0aWZhY3RzKCkpCiAgICAgICAgX3dyaXRlX2Rpc2NvdmVyZWQoY29uKQogICAgICAgIGNvbi5jb21taXQoKQogICAgZmluYWxseToKICAgICAgICBjb24uY2xvc2UoKQogICAgcmV0dXJuIHBhdGgKCgppZiBfX25hbWVfXyA9PSAiX19tYWluX18iOgogICAgb3V0ID0gc3lzLmFyZ3ZbMV0gaWYgbGVuKHN5cy5hcmd2KSA+IDEgZWxzZSAiZGVtby5kYiIKICAgIHdyaXRlX2RlbW8ob3V0KQogICAgcHJpbnQoIndyb3RlIGRlbW8gbGVkZ2VyOiIsIG91dCkK
"""


def _die(msg, code=2):
    print("fix_demo: " + msg)
    sys.exit(code)


def main():
    pb = os.path.join(HERE, "payload_builder.py")
    if not os.path.exists(pb):
        _die("no payload_builder.py in this folder (" + HERE + ").\n"
             "  Put fix_demo.py in your docket/ folder, beside payload_builder.py, "
             "and run it from there.")

    target = os.path.join(HERE, "_demo_ledger.py")
    if os.path.exists(target):
        bak = target + ".bak-" + time.strftime("%Y%m%d-%H%M%S")
        with open(target, "rb") as f:
            old = f.read()
        with open(bak, "wb") as f:
            f.write(old)
        print("backed up old _demo_ledger.py -> " + os.path.basename(bak))
    else:
        print("no existing _demo_ledger.py; writing a fresh one.")

    data = base64.b64decode(_DEMO_B64.encode())
    with open(target, "wb") as f:
        f.write(data)
    print("wrote CONTRACT-driven _demo_ledger.py (" + str(len(data)) + " bytes)")

    # clear any stale bytecode so the new module is used
    pycache = os.path.join(HERE, "__pycache__")
    if os.path.isdir(pycache):
        for n in os.listdir(pycache):
            if n.startswith("_demo_ledger") or n.startswith("payload_builder"):
                try:
                    os.remove(os.path.join(pycache, n))
                except OSError:
                    pass

    print("")
    print("=" * 60)
    print("running self-tests")
    print("=" * 60)
    any_fail = False
    for script in ("payload_builder.py", "report.py", "serve.py"):
        path = os.path.join(HERE, script)
        if not os.path.exists(path):
            continue
        print("\n$ python " + script + " --self-test")
        r = subprocess.run([sys.executable, path, "--self-test"],
                           cwd=HERE, capture_output=True, text=True)
        out = (r.stdout or "") + (r.stderr or "")
        # show the last few lines (the tally, and any FAIL lines)
        tail = [ln for ln in out.splitlines()
                if ln.strip() and ("FAIL" in ln or "self-test" in ln
                                   or "self test" in ln or "Traceback" in ln
                                   or "Error" in ln)]
        for ln in (tail[-12:] if tail else out.splitlines()[-5:]):
            print("  " + ln)
        if r.returncode != 0:
            any_fail = True

    print("")
    print("=" * 60)
    if any_fail:
        print("Some self-tests still report failures above.")
        print("If the ONLY failures mention key_column, enum, or 'id', those are")
        print("default-schema assumptions in the test, not problems with your")
        print("ledger - your real dashboard is verified by:")
        print("    python payload_builder.py --db ledger.db --doctor")
        print("Send me the FAIL lines and I will adjust.")
    else:
        print("All self-tests green. The demo now matches your CONTRACT.")
    print("Your old demo is preserved as the .bak file next to _demo_ledger.py.")
    print("=" * 60)
    return 1 if any_fail else 0


if __name__ == "__main__":
    sys.exit(main())
