#!/usr/bin/env python3
"""
reset_workbench - return this docket folder to ship-clean state.

Deletes RUN STATE (ledger, caches, per-ticket work, agent memory, reports),
never TOOLING (code, agents, config, tickets templates). Refuses to run
without --yes; prints the doomed paths first either way.

    python reset_workbench.py          # dry run - list what WOULD go
    python reset_workbench.py --yes    # actually reset
    python reset_workbench.py --self-test
"""
from __future__ import annotations

import argparse
import shutil
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent

# Run state: safe to delete, regenerated by the pipeline.
DOOMED_DIRS = ("cache", "development", "memory", "workspaces",
               "__pycache__", "scripts/__pycache__", ".pytest_cache")
DOOMED_FILES = ("ledger.db", "ledger.db-wal", "ledger.db-shm",
                "report.html", ".coverage")


def targets(root):
    out = []
    for d in DOOMED_DIRS:
        p = root / d
        if p.is_dir():
            out.append(p)
    for f in DOOMED_FILES:
        p = root / f
        if p.is_file():
            out.append(p)
    return out


def reset(root, do_it, say=print):
    got = targets(root)
    if not got:
        say("already clean - nothing to remove.")
        return []
    for p in got:
        say("{} {}".format("removing" if do_it else "WOULD remove",
                           p.relative_to(root)))
        if do_it:
            if p.is_dir():
                shutil.rmtree(p, ignore_errors=True)
            else:
                p.unlink(missing_ok=True)
    if not do_it:
        say("dry run - pass --yes to actually reset.")
    return got


def _self_test():
    import tempfile
    checks = []

    def ok(name, cond):
        checks.append((name, bool(cond)))

    with tempfile.TemporaryDirectory() as td:
        root = Path(td)
        (root / "cache" / "proj").mkdir(parents=True)
        (root / "ledger.db").write_text("x", encoding="utf-8")
        (root / "agents").mkdir()
        (root / "agents" / "developer.md").write_text("keep", encoding="utf-8")
        (root / "loop.py").write_text("keep", encoding="utf-8")

        got = reset(root, do_it=False, say=lambda *_: None)
        ok("dry run deletes nothing",
           (root / "ledger.db").exists() and len(got) == 2)
        reset(root, do_it=True, say=lambda *_: None)
        ok("run state removed",
           not (root / "ledger.db").exists() and not (root / "cache").exists())
        ok("tooling untouched",
           (root / "agents" / "developer.md").exists()
           and (root / "loop.py").exists())
        ok("idempotent", reset(root, do_it=True, say=lambda *_: None) == [])

    passed = sum(1 for _, c in checks if c)
    for name, c in checks:
        print("  [{}] {}".format("ok " if c else "XX", name))
    print("\n{}/{} checks passed".format(passed, len(checks)))
    return passed == len(checks)


def main(argv=None):
    ap = argparse.ArgumentParser(description="reset docket to ship-clean")
    ap.add_argument("--yes", action="store_true")
    ap.add_argument("--self-test", action="store_true")
    args = ap.parse_args(argv)
    if args.self_test:
        sys.exit(0 if _self_test() else 1)
    reset(HERE, do_it=args.yes)


if __name__ == "__main__":
    main()
