#!/usr/bin/env python3
"""
run_context - the run's shared blackboard: one curated JSON file per run that
carries facts, stage outcomes and short notes FORWARD to later agents, with
per-stage visibility rules.

Why this exists: Docket is ~10 agents passing artifacts through gates, and
every hand-off used to drop context - QA never learned which tasks escalated,
the retro never saw what the developer discovered ("that HTML file is
generated - edit the generator"). A single Claude-Code-style shared transcript
is the wrong fix here: agents are stateless calls, so shared context is
re-sent tokens on every call, and one gate (blind review) is only worth
anything BECAUSE it shares nothing. So: small, structured, curated, and
per-stage visibility instead of one big transcript.

Rules (the invariants, applied):
  - Deterministic code writes this file. Agents may CONTRIBUTE short notes
    through their done payloads, but a stage script records them - the file is
    never model-written, and no outcome in it is self-reported.
  - blind_review and security see NOTHING. The blindness is a stated rule
    here, not an accident of wiring.
  - Every render is capped. The blackboard must never become the token burn
    it was built to avoid.

Self-test:  python scripts/run_context.py --self-test
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

FILE_NAME = "run-context.json"
MAX_NOTE_CHARS = 300
MAX_NOTES = 30
DEFAULT_RENDER_CAP = 2500

# stage -> sections it may see. Absent stage = sees nothing (safe default).
# blind_review/security are listed explicitly so the blindness is a decision
# a reader can find, not an omission.
VISIBILITY = {
    "developer": ("facts", "outcomes", "notes"),
    "qa": ("facts", "outcomes", "notes"),
    "lead_qa": ("facts", "outcomes", "notes"),
    "mutation": ("outcomes", "notes"),
    "retro": ("facts", "outcomes", "notes"),
    "blind_review": (),
    "security": (),
}


def path_for(dev_dir):
    return Path(dev_dir) / FILE_NAME


def _load(dev_dir):
    p = path_for(dev_dir)
    if not p.exists():
        return {"facts": {}, "outcomes": [], "notes": []}
    try:
        return json.loads(p.read_text(encoding="utf-8"))
    except Exception as e:
        print("[run_context] unreadable {} ({}) - starting fresh".format(p, e),
              file=sys.stderr)
        return {"facts": {}, "outcomes": [], "notes": []}


def _save(dev_dir, ctx):
    p = path_for(dev_dir)
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(json.dumps(ctx, indent=2), encoding="utf-8")


def add_fact(dev_dir, key, value):
    """A stable fact of the run (ticket intent, radius files, plan approach).
    Deterministic callers only."""
    ctx = _load(dev_dir)
    ctx["facts"][str(key)] = value
    _save(dev_dir, ctx)


def stage_outcome(dev_dir, stage, outcome, reason=None, extra=None):
    """Record how a stage ended. Appended, never rewritten - a re-run of a
    stage appends a second entry and the render shows the latest per stage."""
    ctx = _load(dev_dir)
    entry = {"stage": str(stage), "outcome": str(outcome)}
    if reason:
        entry["reason"] = str(reason)[:400]
    if extra:
        entry["extra"] = extra
    ctx["outcomes"].append(entry)
    _save(dev_dir, ctx)


def note(dev_dir, actor, text):
    """A short fact worth carrying forward ('X.html is generated by gen.py').
    Capped hard: notes are for the next agent, not a diary."""
    text = str(text or "").strip()
    if not text:
        return
    ctx = _load(dev_dir)
    if len(ctx["notes"]) >= MAX_NOTES:
        return
    ctx["notes"].append({"actor": str(actor)[:40], "text": text[:MAX_NOTE_CHARS]})
    _save(dev_dir, ctx)


def render_for(dev_dir, stage, cap=DEFAULT_RENDER_CAP):
    """The capped digest a stage may inject into its prompt. Empty string when
    the stage sees nothing (blind review, unknown stages) or nothing recorded."""
    sections = VISIBILITY.get(stage, ())
    if not sections:
        return ""
    ctx = _load(dev_dir)
    out = []
    if "facts" in sections and ctx["facts"]:
        out.append("FACTS:")
        for k, v in list(ctx["facts"].items())[:12]:
            out.append("  {}: {}".format(k, str(v)[:200]))
    if "outcomes" in sections and ctx["outcomes"]:
        latest = {}
        for e in ctx["outcomes"]:
            latest[e["stage"]] = e
        out.append("STAGE OUTCOMES SO FAR:")
        for e in latest.values():
            line = "  {}: {}".format(e["stage"], e["outcome"])
            if e.get("reason"):
                line += " ({})".format(e["reason"][:160])
            out.append(line)
    if "notes" in sections and ctx["notes"]:
        out.append("NOTES FROM EARLIER AGENTS:")
        for n in ctx["notes"][-10:]:
            out.append("  [{}] {}".format(n["actor"], n["text"]))
    if not out:
        return ""
    body = "=== RUN CONTEXT (recorded by the pipeline) ===\n" + "\n".join(out)
    if len(body) > cap:
        body = body[:cap] + "\n... (run context capped at {} chars)".format(cap)
    return body


# ==================================================================== self-test

def _self_test():
    import tempfile

    checks = []

    def ok(name, cond):
        checks.append((name, bool(cond)))

    with tempfile.TemporaryDirectory() as td:
        ok("empty context renders empty", render_for(td, "qa") == "")

        add_fact(td, "ticket_intent", "add JSON source support")
        stage_outcome(td, "frozen_tests", "pass", extra={"tests": 31})
        stage_outcome(td, "unit_tests", "fail",
                      reason="2 task(s) escalated - work incomplete: task-01, task-02")
        note(td, "developer", "test_case_form.html is GENERATED by gen.py - "
                              "edit the generator, not the file")

        r = render_for(td, "qa")
        ok("qa sees facts", "add JSON source support" in r)
        ok("qa sees outcomes", "unit_tests: fail" in r and "escalated" in r)
        ok("qa sees notes", "edit the generator" in r)

        ok("BLIND REVIEW SEES NOTHING", render_for(td, "blind_review") == "")
        ok("security sees nothing", render_for(td, "security") == "")
        ok("unknown stage sees nothing (safe default)",
           render_for(td, "somebody_new") == "")

        ok("mutation sees outcomes but not facts",
           "unit_tests" in render_for(td, "mutation")
           and "add JSON source" not in render_for(td, "mutation"))

        # Latest outcome per stage wins in the render; history is kept on disk.
        stage_outcome(td, "unit_tests", "pass")
        ok("re-run stage shows its LATEST outcome",
           "unit_tests: pass" in render_for(td, "qa")
           and "unit_tests: fail" not in render_for(td, "qa"))
        ok("history preserved on disk",
           sum(1 for e in _load(td)["outcomes"] if e["stage"] == "unit_tests") == 2)

        # Caps hold.
        note(td, "developer", "x" * 5000)
        ok("notes capped", all(len(n["text"]) <= MAX_NOTE_CHARS
                               for n in _load(td)["notes"]))
        for i in range(50):
            note(td, "a", "note {}".format(i))
        ok("note count capped", len(_load(td)["notes"]) <= MAX_NOTES)
        ok("render capped", len(render_for(td, "qa", cap=400)) <= 460)

        note(td, "dev", "")
        ok("empty note dropped", all(n["text"] for n in _load(td)["notes"]))

        # A corrupt file degrades to fresh, loudly on stderr, never crashes.
        path_for(td).write_text("{ this is not json", encoding="utf-8")
        ok("corrupt file degrades to fresh", render_for(td, "qa") == "")

    passed = sum(1 for _, c in checks if c)
    for name, c in checks:
        print("  [{}] {}".format("ok " if c else "XX", name))
    print("\n{}/{} checks passed".format(passed, len(checks)))
    return passed == len(checks)


def main(argv=None):
    ap = argparse.ArgumentParser(description="Docket run-context blackboard")
    ap.add_argument("--self-test", action="store_true")
    args = ap.parse_args(argv)
    if args.self_test:
        sys.exit(0 if _self_test() else 1)
    ap.print_help()
    return 0


if __name__ == "__main__":
    main()
